name: map2seq
channels:
  - conda-forge
  - bioconda
  - pytorch
dependencies:
  - python=3.9
  - numpy=1.22.3
  - h5py
  - pandas=1.4.4
  - scipy=1.8.0
  - cctbx-base=2022.4
  - hmmer
  - pyfastx
  - bokeh=2.4.3
  - pytorch=1.11.0
