name: findmysequence
channels:
  - bioconda
  - conda-forge
dependencies:
  - pip
  - pip:
    - bokeh
    - h5py
    - numpy
    - pandas
    - scipy
    - streamlit
    - torch
  - cctbx-base 
  - hmmer
