name: findmysequence
channels:
  - bioconda
  - conda-forge
dependencies:
  - cctbx
  - bokeh
  - h5py
  - numpy
  - onnx
  - onnxruntime
  - pandas
  - scipy
  - streamlit
  - tensorflow
  - pytorch
  - hmmer
