name: findmysequence
channels:
  - bioconda
  - conda-forge
  - gchojnowski
dependencies:
  - pip
  - cctbx-base 
  - hmmer
  - findmysequence
  - pip:
    - bokeh
    - h5py
    - numpy
    - pandas
    - scipy
    - streamlit
    - torch
    - scitbx
    - scikit-learn
    - statsmodels
