name: map2seq
channels:
  - conda-forge
  - bioconda
  - pytorch
dependencies:
  - python=3.9
  - numpy
  - h5py
  - pandas
  - scipy
  - cctbx-base
  - hmmer
  - pyfastx
  - bokeh
  - pytorch
  - pip
  - pip:
    - stmol
