name: map2seq
channels:
  - bioconda
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - numpy
  - h5py
  - pandas
  - scipy
  - cctbx-base
  - hmmer
  - bokeh
  - pytorch
  - pip
  - pip:
    - streamlit
