name: findmysequence
channels:
  - bioconda
  - conda-forge
dependencies:
  - pip
  - cctbx-base 
  - hmmer
  - pip:
    - bokeh==2.4.2
    - h5py==3.6.0
    - numpy==1.22.4
    - onnx==1.11.0
    - onnx2keras==0.0.24
    - onnx_tf==1.10.0
    - onnxruntime==1.11.1
    - pandas
    - scipy==1.7.3
    - scitbx==0.0.31
    - streamlit==1.9.1
    - tensorflow==2.9.1
    - torch==1.11.0
    - torchsummary==1.5.1
