name: map2seq
channels:
  - conda-forge
dependencies:
<<<<<<< HEAD
  - numpy
  - h5py
  - pandas
  - scipy
  - cctbx-base
  - hmmer
  - bokeh
  - pytorch
=======
  - streamlit
>>>>>>> b35b278b459bb0475e1e4c3e0e59649239a450a9
