name: findmysequence
channels:
  - bioconda
  - conda-forge
dependencies:
  - cctbx
  - bokeh
  - h5py
  - numpy
  - onnx
  - onnx2keras
  - onnx_tf
  - onnxruntime
  - pandas
  - scipy
  - scitbx
  - streamlit
  - tensorflow
  - torch
  - torchsummary
  - hmmer
